runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /(.*\.(gif|png|jpg|js|html|css|json|txt|ico|svg|xml))$
  static_files: www/\1
  upload: www/.*\.(gif|png|jpg|js|html|css|json|txt|ico|svg|xml)$

- url: /(.*)
  secure: always
  redirect_http_response_code: 301
  static_files: www/index.html
  upload: www/index.html
