/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    sidebar: [
        {
            type: 'doc',
            id: 'introduction',
        },
        {
            type: 'doc',
            id: 'toplevel',
        },
        {
            type: 'doc',
            id: 'types',
        },
        {
            type: 'doc',
            id: 'testing',
        },
        {
            type: 'category',
            collapsed: false,
            collapsible: false,
            label: 'Guides',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'guides',
                },
            ],
        },
    ],
};

module.exports = sidebars;
